### ISSUE TITLE
Explorar atualizacao censo 2022

### ISSUE THREAD

**Issue by mathhmz** [sepep-pmsp/hydra#67]
https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html?=&t=resultados

21/03 - Novos dados do censo de 2022 foram disponibilizados ao público e precisam ser avaliados para integração com as funcionalidades atuais do Hydra; 

- [x] Houve mudança nos setores censitários?
- [x] Comparar número total de setores com domicílios particulares; 
- [x] Avaliar a diferenças das geometrias (polígonos);

Setor censitário 2010 x 2022

- [x] Formato dos dados mudou?
- [x] Distritos mudaram?
- [x] Critérios alterados?

**Comment by brunoazuma** [comment]
A avaliação deu origem a outro projeto, o https://github.com/sepep-pmsp/compatibilizacao-setores-censitarios
